variables:
  DOCKER_REGISTRY: "docker.grammatech.com:14850"
  LOCAL_IMAGE_NAME: '$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'

stages:
  - build-deploy-cleanup

.build-template: &build
  script:
    - cp /u4/TARBALLS/datalog_disasm/standalone_compilation.tar.bz2 ./
    - (cd tests ; ./fetch_real_examples.sh)
    - docker build -f .ci/Dockerfile.$OS -t ${LOCAL_IMAGE_NAME}-${OS} .
    - docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}:latest;
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}:latest;
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}

build-ubuntu16:
  stage: build-deploy-cleanup
  variables:
    OS: 'ubuntu16'
  <<: *build

build-arch:
  stage: build-deploy-cleanup
  variables:
    OS: 'arch'
  <<: *build
